site_name: HAlpha
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - mkdocstrings
  - git-revision-date-localized:
      type: date
  - git-authors
  - tags

nav:
  - Home: index.md
  - Overview: overview.md
  - Installation Guide: 
    - Overview: installation-guide/overview.md
    - Install pre built Image: installation-guide/installation.md
    - Installation from Scratch: installation-guide/install-scratch.md
    - Troubleshooting: installation-guide/trouble.md
  - How-To Guides: 
    - Livestream: how-to-guides/how-to-guide-livestream.md
    - Seting focus: how-to-guides/how-to-guide-set-focus.md
  - Reference:
    - Camera Control: reference/cameracontrol.md
    - Alignment: reference/alignment.md
    - Image Processing: reference/image_processing.md
    - Server upload: reference/upload.md
  - Hardware: hardware.md
  
repo_url: https://github.com/pmodwrc/halpha 
repo_name: HAlpha



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js