site_name: Halpha
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Overview: index.md
  -Installation Guide: installation.md
  - How-To Guides: 
    - Livestream: how_to_guides/how-to-guide-livestream.md
    - Set_focus: how_to_guides/how-to-guide-set-focus.md
  - Reference:
    - Camera Control: reference/cameracontrol.md
    - Alignment: reference/alignment.md
    - Image Processing: reference/image_processing.md
    - Server upload: reference/upload.md
  -Hardware: harware.md
  
  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js